### ISSUE TITLE
My players are reporting language problems and I think I know what

### ISSUE THREAD

**Issue by eyal282** [abnerfs/abner_duel#12]
CPrintToChat may not iterate every player, set them as SetGlobalTransTarget before printing, meaning that it's possible that one player may dictate the entire language to all other players, resulting in one russian player giving all players a russian translation. Can you look into it?

**Comment by abnerfs** [comment]
Is this issue still happening?

**Comment by eyal282** [comment]
I legitimately do not remember this issue. 3 years is too long for me to remember what bug I complained about.

If SetGlobalTransTarget is not ran per player, the issue should occur.
If it's ran globally, that player will dictate everybody's translations

**Comment by abnerfs** [comment]
It is run per player I assure
