### ISSUE TITLE
Some errors ...

### ISSUE THREAD

**Issue by TR1D** [abnerfs/abner_duel#3]
https://youtu.be/QDrHdOkr_VE
https://youtu.be/a6lhQIxpK3A

I think better to use the old method duel.
1. Remove the current weapon
2. Waiting
3. Give weapons for a duel.

And need to block the ability to drop weapon.
During the duel.

And if a player is disconnected during the duel, need automatically stop a duel.

And it is not necessary to remove the knife

**Comment by TR1D** [comment]
I'll try fix4

**Comment by TR1D** [comment]
https://youtu.be/QDrHdOkr_VE

**Comment by TR1D** [comment]
And need to block the ability to drop weapon.
During the duel.

**Comment by TR1D** [comment]
And https://youtu.be/a6lhQIxpK3A

**Comment by TR1D** [comment]
And if a player is disconnected during the duel, you want to automatically stop a duel.

**Comment by TR1D** [comment]
Still here ?

**Comment by abnerfs** [comment]
Try new version 4.0.0
