### ISSUE TITLE
[Feature Request] Compatible with Multi1v1

### ISSUE THREAD

**Issue by crashzk** [abnerfs/abner_duel#4]
Would it be possible to make this plugin compatible with the Multi1v1 plugin?

I have already tried several plugins with this function, duel no-scope x1 but I never find a compatible one for Multi1v1.

Or even a same version of the plugin, in case in another repo, only compatible with multi1v1.

**Comment by abnerfs** [comment]
Plz give me the link for multi 1v1 repo and I will analyze

**Comment by crashzk** [comment]
https://github.com/splewis/csgo-multi-1v1

Done, thanks, I'll be waiting.

**Comment by abnerfs** [comment]
How do you think my plugin can be used with multi 1v1, what is your idea?

**Comment by crashzk** [comment]
In case it would be that other third party plugins that have for Multi1v1, here are some examples:
https://forums.alliedmods.net/showthread.php?p=2583400
https://forums.alliedmods.net/showthread.php?p=2373966
https://forums.alliedmods.net/showthread.php?p=2541921

That is, it would be custom rounds, which players choose or do not activate for them to have as an option.

However, by researching examples for you, I found one that would seemingly be what I want: https://forums.alliedmods.net/showthread.php?t=300406

However, it has been removed from AlliedModders.

**Comment by crashzk** [comment]
I ended up finding an old version and with some requests on the topic a new user redone the plugin again.

https://forums.alliedmods.net/showthread.php?t=314082

Thank you anyway.

**Comment by abnerfs** [comment]
Anyway I will analyze a way to implement this in the future, thanks for your suggestion
