### ISSUE TITLE
Issue when trying to open the !duel with 4.0

### ISSUE THREAD

**Issue by Vorliz** [abnerfs/abner_duel#5]
Hi, just installed this version of the mod, and this error appeared after typing !duel on chat:
"L 02/02/2019 - 21:06:43: [SM] Exception reported: Language phrase "Always Accept" not found (arg 5)
L 02/02/2019 - 21:06:43: [SM] Blaming: abner_duel.smx
L 02/02/2019 - 21:06:43: [SM] Call stack trace:
L 02/02/2019 - 21:06:43: [SM]   [0] Format
L 02/02/2019 - 21:06:43: [SM]   [1] Line 212, d:\Abner\abner_duel\scripting\abner_duel.sp::DuelMenu"
could you help me?
Thanks, Vorliz

**Comment by abnerfs** [comment]
Sorry I forgot the translations folder, download it again plz
