### ISSUE TITLE
Handle 99d308c2 is invalid (error 3)

### ISSUE THREAD

**Issue by usershtopor** [abnerfs/abner_duel#7]
Hi, AbNeR.
Fix errors, please

SM 1.9.0.6275
AbNeR Duel 4.0.2

L 02/15/2019 - 20:59:24: [SM]   [1] Line 408, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler
L 02/15/2019 - 21:00:38: [SM] Exception reported: Handle 99d308c2 is invalid (error 3)
L 02/15/2019 - 21:00:38: [SM] Blaming: source_games/duel.smx
L 02/15/2019 - 21:00:38: [SM] Call stack trace:
L 02/15/2019 - 21:00:38: [SM]   [0] CloseHandle
L 02/15/2019 - 21:00:38: [SM]   [1] Line 408, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler
L 02/15/2019 - 21:02:36: [SM] Exception reported: Handle 9d0508ca is invalid (error 3)
L 02/15/2019 - 21:02:36: [SM] Blaming: source_games/duel.smx
L 02/15/2019 - 21:02:36: [SM] Call stack trace:
L 02/15/2019 - 21:02:36: [SM]   [0] CloseHandle
L 02/15/2019 - 21:02:36: [SM]   [1] Line 408, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler
L 02/15/2019 - 21:03:47: [SM] Exception reported: Handle 9fcc08bf is invalid (error 3)
L 02/15/2019 - 21:03:47: [SM] Blaming: source_games/duel.smx
L 02/15/2019 - 21:03:47: [SM] Call stack trace:
L 02/15/2019 - 21:03:47: [SM]   [0] CloseHandle
L 02/15/2019 - 21:03:47: [SM]   [1] Line 408, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler
L 02/15/2019 - 21:04:42: [SM] Exception reported: Handle a1c608b9 is invalid (error 3)
L 02/15/2019 - 21:04:42: [SM] Blaming: source_games/duel.smx
L 02/15/2019 - 21:04:42: [SM] Call stack trace:
L 02/15/2019 - 21:04:42: [SM]   [0] CloseHandle
L 02/15/2019 - 21:04:42: [SM]   [1] Line 408, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler
L 02/15/2019 - 21:05:28: [SM] Exception reported: Handle a37008c2 is invalid (error 3)
L 02/15/2019 - 21:05:28: [SM] Blaming: source_games/duel.smx
L 02/15/2019 - 21:05:28: [SM] Call stack trace:
L 02/15/2019 - 21:05:28: [SM]   [0] CloseHandle
L 02/15/2019 - 21:05:28: [SM]   [1] Line 408, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler
L 02/15/2019 - 21:06:30: [SM] Exception reported: Handle a51f08c3 is invalid (error 3)
L 02/15/2019 - 21:06:30: [SM] Blaming: source_games/duel.smx
L 02/15/2019 - 21:06:30: [SM] Call stack trace:
L 02/15/2019 - 21:06:30: [SM]   [0] CloseHandle
L 02/15/2019 - 21:06:30: [SM]   [1] Line 408, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler

**Comment by abnerfs** [comment]
I think i found the problem, will try to solve soon...

**Comment by abnerfs** [comment]
Try https://github.com/abnerfs/abner_duel/releases/tag/v4.0.3

**Comment by usershtopor** [comment]
Plugin v4.0.3
Please, fix it

L 02/16/2019 - 12:37:33: SourceMod error session started
L 02/16/2019 - 12:37:33: Info (map "workshop/487039571/awp_lego_2") (file "errors_20190216.log")
L 02/16/2019 - 12:37:33: [SM] Exception reported: Handle 36b00874 is invalid (error 3)
L 02/16/2019 - 12:37:33: [SM] Blaming: source_games/duel.smx
L 02/16/2019 - 12:37:33: [SM] Call stack trace:
L 02/16/2019 - 12:37:33: [SM]   [0] CloseHandle
L 02/16/2019 - 12:37:33: [SM]   [1] Line 406, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler
L 02/16/2019 - 12:38:24: [SM] Exception reported: Handle 36fa0876 is invalid (error 3)
L 02/16/2019 - 12:38:24: [SM] Blaming: source_games/duel.smx
L 02/16/2019 - 12:38:24: [SM] Call stack trace:
L 02/16/2019 - 12:38:24: [SM]   [0] CloseHandle
L 02/16/2019 - 12:38:24: [SM]   [1] Line 406, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler
L 02/16/2019 - 12:39:01: [SM] Exception reported: Handle 376f0879 is invalid (error 3)
L 02/16/2019 - 12:39:01: [SM] Blaming: source_games/duel.smx
L 02/16/2019 - 12:39:01: [SM] Call stack trace:
L 02/16/2019 - 12:39:01: [SM]   [0] CloseHandle
L 02/16/2019 - 12:39:01: [SM]   [1] Line 406, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler

**Comment by abnerfs** [comment]
Try https://github.com/abnerfs/abner_duel/releases/tag/v4.0.4

**Comment by usershtopor** [comment]
L 02/16/2019 - 14:03:43: SourceMod error session started
L 02/16/2019 - 14:03:43: Info (map "workshop/487039571/awp_lego_2") (file "errors_20190216.log")
L 02/16/2019 - 14:03:43: [SM] Exception reported: Handle 1a290860 is invalid (error 3)
L 02/16/2019 - 14:03:43: [SM] Blaming: source_games/duel.smx
L 02/16/2019 - 14:03:43: [SM] Call stack trace:
L 02/16/2019 - 14:03:43: [SM]   [0] CloseHandle
L 02/16/2019 - 14:03:43: [SM]   [1] Line 407, D:\Distrib\srcds\03 Sourcemod\sourcemod-1.9.0-git6260-windows\duel.sp::VoteMenuHandler

**Comment by abnerfs** [comment]
I removed the line with error  
try https://github.com/abnerfs/abner_duel/releases/tag/v4.0.5

**Comment by usershtopor** [comment]
ok. thx. plugin works
