### ISSUE TITLE
Vote popup disappears after one person accepts duel

### ISSUE THREAD

**Issue by zeeklol** [abnerfs/abner_duel#8]
When both players have !duel option set to "Decide in vote" and one person accepts the duel, the other cannot. It works fine if one person has the option set to "Always accept" and the other person has it set to "Decide in vote". The only problem is when both players have "Decide in vote" selected. 

Video [after he accepts the vote (presses 1), I cannot accept it.] -> https://streamable.com/zmzud

edit: Server just crashes with the newest version, had to go back to v 4.0.1
edit2: https://pastebin.com/03viuCkD logs of the newest version of plugin, still crashes the server.

**Comment by abnerfs** [comment]
Try the new release [4.0.8](https://github.com/abnerfs/abner_duel/releases/tag/v4.0.8)

**Comment by zeeklol** [comment]
Yep vote works perfectly fine now.

Pretty sure my server just has a problem now since when the duel starts, no one gets/can pick up the scouts. 

Thanks for your help.
https://pastebin.com/nHWPbsHY

**Comment by abnerfs** [comment]
That's a know issue, I will try to fix it, it's weird

https://github.com/shanapu/MyJailbreak/issues/168

**Comment by abnerfs** [comment]
Try new release [4.0.9](https://github.com/abnerfs/abner_duel/releases/tag/v4.0.9)

**Comment by zeeklol** [comment]
Works. 

Another issue (no errors in logs)- After duel ends, the winner's ssg08 gets replaced by an AWP+Knife or just removes their ssg08 (left only with knife). You can however still pick up scouts on the ground left by the dead player. 
video 1 (removes scout, gives awp and knife)-> https://streamable.com/z5132
video 2 (removes scout, gives only knife)->https://streamable.com/5yfxx

Also, is it possible to make it so that the knife you get in the duel deals no damage? If not, that's fine.

Thanks for your help, once again.

**Comment by abnerfs** [comment]
Sorry for the delay, i'm closing this issue, could you please open a new one with the other bug if it is still happening to you?
